// Zentrale SELECT-Strings für Supabase Queries
// Verhindert 400-Fehler durch nicht existierende Felder

export const TOUR_SELECT = `
  id,
  tour_id,
  driver_id,
  company_id,
  tour_title,
  pickup_address,
  delivery_address,
  customer_name,
  scheduled_pickup_from,
  scheduled_pickup_to,
  scheduled_delivery_from,
  scheduled_delivery_to,
  status,
  priority,
  assigned_at,
  updated_at,
  confirmed_at,
  picked_up_at,
  delivered_at,
  current_location,
  pieces_delivered,
  gps_tracking_active,
  cancellation_reason,
  cancelled_at,
  cancelled_by,
  started_at,
  approved_at,
  approved_by,
  final_compensation,
  approval_notes,
  is_recurring,
  recurring_days,
  recurring_tour_id,
  is_multi_stop,
  stops,
  compensation_type,
  compensation_rate,
  calculated_compensation,
  license_plate,
  fuel_report_id,
  fuel_report_status,
  driver_email,
  driver_name,
  documentation_requirements,
  documentation_completed,
  documentation_status,
  tour_category,
  client_id,
  client_name,
  handed_off_from_company_id,
  handed_off_to_company_id,
  handoff_status,
  handoff_offered_at,
  handoff_accepted_at,
  handoff_message
`;

export const DRIVER_DOCUMENTS_SELECT = `
  id,
  driver_id,
  driver_email,
  driver_name,
  company_id,
  document_type,
  file_path,
  file_size,
  uploaded_at,
  created_at,
  updated_at
`;

export const TRAFFIC_VIOLATIONS_SELECT = `
  id,
  driver_id,
  tour_id,
  vehicle_id,
  violation_type,
  custom_label,
  status,
  amount,
  currency,
  violation_date,
  reference_number,
  due_date,
  notes_company,
  paid_at,
  cancelled_at,
  cancelled_reason,
  has_pdf,
  created_at,
  updated_at
`;

export const DRIVER_PAYMENTS_SELECT = `
  id,
  driver_id,
  driver_email,
  amount,
  payment_date,
  period_start,
  period_end,
  status,
  payment_method,
  notes,
  created_at
`;

export const FUEL_REPORTS_SELECT = `
  id,
  driver_id,
  driver_email,
  amount,
  liters,
  odometer_reading,
  receipt_photo_url,
  vehicle_id,
  station_name,
  fuel_type,
  submitted_at,
  approved_at,
  rejected_at,
  rejection_reason,
  created_at
`;